name: GitHub Release
concurrency: deployment
on:
  push:
    branches:
      - main
      - release/*

permissions:
  contents: write

jobs:
  release-me:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Run ReleaseMe
        id: release
        uses: dev-build-deploy/release-me@v0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
